<?php

function mannird9_theme($existing, $type, $theme, $path) {

  return [
    'registration' => [
      'path' => $path . '/templates',
      'template'  => 'registration',
      'render element' => 'elements',
      'base_path' => base_path(),
      'variables' => [
        'reg' => NULL,
      ],
    ],
  ];
}


function sendsms($phone, $message) {
  $message = str_replace(' ', '%20', $message);

  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => 'http://www.smslive247.com/http/index.aspx?cmd=sendquickmsg&owneremail=sms@brilliant.ng&subacct=123&subacctpwd=123&message='.$message.'&sender=IGR&sendto='.$phone.'&msgtype=0%0A',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
  ));

  $response = curl_exec($curl);

  curl_close($curl);

  return $response;
}
